### PR TITLE
Fix Ruby 2.7 warnings

### LINKED ISSUE #35: Fix warning : URI.escape is obsolete
**Describe the bug**
When I use kt-paperclip on a Rails 6.0.3 application powered by Ruby 2.7.1 my logs are filled with this warning :

`/home/pierre/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kt-paperclip-6.3.0/lib/paperclip/url_generator.rb:68: warning: URI.escape is **obsolete**`

**To Reproduce**
Run a rails application with kt-paperclip on Ruby 2.7+

**Expected behavior**
No warnings are logged

**Additional context**
The `URI.escape` [documentation](https://ruby-doc.org/stdlib-2.7.1/libdoc/uri/rdoc/URI/Escape.html#method-i-escape-label-Description) has this statement:

```
    # This method is obsolete and should not be used. Instead, use
    # CGI.escape, URI.encode_www_form or URI.encode_www_form_component
    # depending on your specific use case.
``` 

Several Ruby projects have fixed this error, example: https://github.com/contentful/contentful.rb/pull/221/commits/82dd6df17caed705e67f2737282c97764c25d2b3#diff-606706a8b47f20495c7c206d12212665

### PR DESCRIPTION
**Pull request by kikihakiem**
This PR fixes #35

### CODE REVIEW

**Comment by kikihakiem** [comment]
@ssinghi `URI.escape` and other methods  use `RFC2396_Parser` internally. I see that in Ruby 3.0 preview that class is not removed, so I think we can use it if we want the exact same behaviour as `URI.escape` without introducing a new dependency. Please review

**Review by Kevinrob — APPROVED** [review]

**Review by shalinibhawsingka-kreeti — APPROVED** [review]

**Comment by ssinghi** [comment]
Thank you @kikihakiem for this PR, appreciate it.
Thank you @shalinibhawsingka-kreeti and @Kevinrob for the review.

**Comment by adrijere** [comment]
Thank you guys for your hard work! Is it possible to do a release with a new tag with the fix please @ssinghi :) ?

**Comment by xdmx** [comment]
Definitely a plus one on the above, I'd love to see a new version released to fix all warnings, without having to fetch the code through git. Also considering that Xmas and 3.0 are near :santa:

**Comment by ghiculescu** [comment]
for those who missed it, https://github.com/kreeti/kt-paperclip/releases/tag/v6.4.0 is live now

**Comment by masterkain** [comment]
I still have

`/bundle/vendor/ruby/2.7.0/bundler/gems/kt-paperclip-76b168fbe68d/lib/paperclip/io_adapters/uri_adapter.rb:56: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open`

**Pull request merged**
